# Generated by Django 3.2.4 on 2021-09-24 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_store_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='store_number',
        ),
    ]
