# Generated by Django 3.2.4 on 2021-09-29 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_remove_location_store_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='image',
        ),
        migrations.RemoveField(
            model_name='location',
            name='image_url',
        ),
    ]
